### PR TITLE
Language tool as maven dependency

### PR DESCRIPTION
**Pull request by vatbub**
Languagetool is now used as a maven dependency (more details in #5)

### CODE REVIEW

**Comment by vogella** [comment]
I prefer to have the project settings for Eclipse projects checked in, to provide the same setup for all developers. Could you remove this commit from the PR?

**Comment by vatbub** [comment]
Here you go :)

**Comment by vogella** [comment]
@vatbub Interactive rebase is your friend to remove a commit. No need to have the commit and the reverted commit in the history. http://www.vogella.com/tutorials/EclipseGit/article.html#using-the-git-interactive-rebase-view

Can you also please update the README.md with the correct build instructions. 

Other than that, this PR is good to go.

**Comment by vatbub** [comment]
Hi,
sorry for not responding, I was quite busy.
I actually prefer reverting as this keeps the history "real" in the sense that one can see that there was a change that has been reverted.

Anyway, I'll update the readme in just a sec.
Regards,
vatbub

**Comment by vatbub** [comment]
Oh, I just saw that you're actually a german company so Servus :)

**Comment by vogella** [comment]
Moin, moin :-)

Am 01.11.2016 10:09 nachm. schrieb "Frederik Kammel" <
notifications@github.com>:

**Comment by vogella** [comment]
Thanks @vatbub 

Looking forward to more fixes from you. For example, if I remember correctly the cursor position did change if I apply a suggestion via quickfix.

**Pull request merged**
